# Importing the libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
data = pd.read_csv(r'D:\books\git\MLzoomcampCapstone_2\data\customer_support_tickets.csv')

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

In [41]:
data.head().T

,0,1,2,3,4
Ticket ID,1,2,3,4,5
Customer Name,Marisa Obrien,Jessica Rios,Christopher Robbins,Christina Dillon,Alexander Carroll
Customer Email,carrollallison@example.com,clarkeashley@example.com,gonzalestracy@example.com,bradleyolson@example.org,bradleymark@example.com
Customer Age,32,42,48,27,67
Customer Gender,Other,Female,Other,Female,Female
Product Purchased,GoPro Hero,LG Smart TV,Dell XPS,Microsoft Office,Autodesk AutoCAD
Date of Purchase,2021-03-22,2021-05-22,2020-07-14,2020-11-13,2020-02-04
Ticket Type,Technical issue,Technical issue,Technical issue,Billing inquiry,Billing inquiry
Ticket Subject,Product setup,Peripheral compatibility,Network problem,Account access,Data loss
Ticket Description,I'm having an issue with the {product_purchase...,I'm having an issue with the {product_purchase...,I'm facing a problem with my {product_purchase...,I'm having an issue with the {product_purchase...,I'm having an issue with the {product_purchase...
Ticket Status,Pending Customer Response,Pending Customer Response,Closed,Closed,Closed
Resolution,NaN,NaN,Case maybe show recently my computer follow.,Try capital clearly never color toward story.,West decision evidence bit.
Ticket Priority,Critical,Critical,Low,Low,Low
Ticket Channel,Social media,Chat,Social media,Social media,Email
First Response Time,2023-06-01 12:15:36,2023-06-01 16:45:38,2023-06-01 11:14:38,2023-06-01 07:29:40,2023-06-01 00:12:42
Time to Resolution,NaN,NaN,2023-06-01 18:05:38,2023-06-01 01:57:40,2023-06-01 19:53:42
Customer Satisfaction Rating,NaN,NaN,3.0,3.0,1.0

we won't use the following features:
- First Response Time	
- Time to Resolution	
- Resolution
- Customer Satisfaction Rating	
- Ticket ID
- Customer Name
- Customer Email

In [42]:
df = data.drop(columns=['First Response Time','Time to Resolution','Resolution',
                            'Customer Satisfaction Rating','Ticket ID','Customer Name',
                            'Customer Email','Ticket Status','Date of Purchase'])

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer Age        8469 non-null   int64
 1   Customer Gender     8469 non-null   object
 2   Product Purchased   8469 non-null   object
 3   Ticket Type         8469 non-null   object
 4   Ticket Subject      8469 non-null   object
 5   Ticket Description  8469 non-null   object
 6   Ticket Priority     8469 non-null   object
 7   Ticket Channel      8469 non-null   object
dtypes: int64(1), object(7)
memory usage: 529.4+ KB

In [44]:
# removing spaces and lowercasing
df.columns = df.columns.str.lower().str.replace(' ', '_')
 
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
 
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')
 
df.head().T

,0,1,2,3,4
customer_age,32,42,48,27,67
customer_gender,other,female,other,female,female
product_purchased,gopro_hero,lg_smart_tv,dell_xps,microsoft_office,autodesk_autocad
ticket_type,technical_issue,technical_issue,technical_issue,billing_inquiry,billing_inquiry
ticket_subject,product_setup,peripheral_compatibility,network_problem,account_access,data_loss
ticket_description,i'm_having_an_issue_with_the_{product_purchase...,i'm_having_an_issue_with_the_{product_purchase...,i'm_facing_a_problem_with_my_{product_purchase...,i'm_having_an_issue_with_the_{product_purchase...,i'm_having_an_issue_with_the_{product_purchase...
ticket_priority,critical,critical,low,low,low
ticket_channel,social_media,chat,social_media,social_media,email

In [19]:
df.dtypes

customer_age           int64
customer_gender       object
product_purchased     object
date_of_purchase      object
ticket_type           object
ticket_subject        object
ticket_description    object
ticket_status         object
ticket_priority       object
ticket_channel        object
dtype: object

In [32]:
df.ticket_priority.value_counts()

ticket_priority
medium      2192
critical    2129
high        2085
low         2063
Name: count, dtype: int64

In [33]:
df[df.ticket_priority=="critical"]

,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,ticket_status,ticket_priority,ticket_channel
0,32,other,gopro_hero,2021-03-22,technical_issue,product_setup,i'm_having_an_issue_with_the_{product_purchase...,pending_customer_response,critical,social_media
1,42,female,lg_smart_tv,2021-05-22,technical_issue,peripheral_compatibility,i'm_having_an_issue_with_the_{product_purchase...,pending_customer_response,critical,chat
6,24,other,microsoft_surface,2020-02-23,product_inquiry,refund_request,i'm_unable_to_access_my_{product_purchased}_ac...,open,critical,social_media
7,23,male,philips_hue_lights,2020-08-09,refund_request,battery_life,i'm_having_an_issue_with_the_{product_purchase...,open,critical,social_media
9,27,male,dyson_vacuum_cleaner,2020-03-06,refund_request,payment_issue,my_{product_purchased}_is_making_strange_noise...,pending_customer_response,critical,phone
...,...,...,...,...,...,...,...,...,...,...
8447,51,other,gopro_hero,2020-07-12,refund_request,installation_support,there_seems_to_be_a_hardware_problem_with_my_{...,pending_customer_response,critical,email
8452,62,female,macbook_pro,2020-03-29,refund_request,display_issue,i'm_having_an_issue_with_the_{product_purchase...,closed,critical,phone
8456,18,female,dyson_vacuum_cleaner,2021-04-08,product_inquiry,payment_issue,i'm_having_an_issue_with_the_{product_purchase...,open,critical,social_media
8462,49,female,samsung_soundbar,2020-10-21,refund_request,display_issue,i'm_having_an_issue_with_the_{product_purchase...,pending_customer_response,critical,email
8465,27,female,bose_soundlink_speaker,2020-02-22,technical_issue,refund_request,i'm_having_an_issue_with_the_{product_purchase...,open,critical,email

In [37]:
df.iloc[9]

customer_age                                                         27
customer_gender                                                    male
product_purchased                                  dyson_vacuum_cleaner
date_of_purchase                                             2020-03-06
ticket_type                                              refund_request
ticket_subject                                            payment_issue
ticket_description    my_{product_purchased}_is_making_strange_noise...
ticket_status                                 pending_customer_response
ticket_priority                                                critical
ticket_channel                                                    phone
Name: 9, dtype: object

In [38]:
print(df.ticket_description[9])

my_{product_purchased}_is_making_strange_noises_and_not_functioning_properly._i_suspect_there_might_be_a_hardware_issue._can_you_please_help_me_with_this?

}_if_we_can,_please_send_a_"request"_to_dav_the_issue_i'm_facing_is_intermittent._sometimes_it_works_fine,_but_other_times_it_acts_up_unexpectedly.

In [45]:
df["text"] = df["ticket_subject"] + " " + df["ticket_description"]

In [50]:
df['text'].iloc[0]

"product_setup i'm_having_an_issue_with_the_{product_purchased}._please_assist.\n\nyour_billing_zip_code_is:_71701.\n\nwe_appreciate_that_you_have_requested_a_website_address.\n\nplease_double_check_your_email_address._i've_tried_troubleshooting_steps_mentioned_in_the_user_manual,_but_the_issue_persists."